print('a1, b1, c1, a2, b2, c2')
a1 = int(input())
b1 = int(input())         
c1 = int(input())
a2 = int(input())
b2 = int(input())
c2 = int(input())
if abs(a1 * b2 - a2 * b1) >= 0.0001:
    print('ok')
    x = (b1*c2-b2*c1)/(a1*b2-a2*b1)
    y = (c1*a2-c2*a1)/(a1*b2-a2*b1)
    print('x' , '=', x)
    print('y' , '=', y)
else:
    print(' Выражение не верно ')